german locale
benjamintd/codenames.cards pull request #60
Opened 2020-11-05 08:23 UTC by benjamintd

Right now it's just the raw output of Deepl. @mwkroening since you submitted a german language PR recently, perhaps you are interested in reviewing this one ? It's probably highly inconsistent and wrong, but my german classes are very far away 😅.

2020-11-05 08:34 UTC, mwkroening commented
Awesome! I'll try to review this later today.

2020-11-05 08:45 UTC, benjamintd commented
Awesome. 
Here is the preview link to see the translations in context: https://codenames-fhlr66zip.vercel.app/de 
Let me know how I can help you :)

2020-11-05 17:32 UTC, mwkroening requested changes
This is a preliminary review.
I suggested many changes and changed the style from “sie” zu “du”.

Generally this is fine, but I could still improve on some wording in the next days. Also, I'll ask a friend to have a look at this as well.

2020-11-05 17:32 UTC, mwkroening commented on locales/de.ts
> +  buymeacoffee: "Unterstützen Sie das Spiel, kaufen Sie mir einen Kaffee",
```suggestion
  buymeacoffee: "Unterstütze das Spiel, kaufe mir einen Kaffee",
```

2020-11-05 17:32 UTC, mwkroening commented on locales/de.ts
> +  "neutral-reaction-1": "Das ist ein Fehlschlag.",
```suggestion
  "neutral-reaction-1": "Das ging daneben.",
```

2020-11-05 17:32 UTC, mwkroening commented on locales/de.ts
> +  "neutral-reaction-2": "Nahe genug.",
Not sure, what this is supposed to mean.

2020-11-05 17:32 UTC, mwkroening commented on locales/de.ts
> +  "neutral-reaction-4": "Das war ein Zivilist.",
```suggestion
  "neutral-reaction-4": "Das war ein unbeteiligter Zuschauer.",
```

2020-11-05 17:32 UTC, mwkroening commented on locales/de.ts
> +  "black-reaction-1": "Sie haben gerade das Spiel verloren!",
```suggestion
  "black-reaction-1": "Ihr habt gerade das Spiel verloren!",
```

2020-11-05 17:32 UTC, mwkroening commented on locales/de.ts
> +  "black-reaction-2": "Die andere Mannschaft gewinnt!",
```suggestion
  "black-reaction-2": "Das andere Team gewinnt!",
```

2020-11-05 17:32 UTC, mwkroening commented on locales/de.ts
> +  "black-reaction-3": "Ihre Mannschaft verliert ☠️",
```suggestion
  "black-reaction-3": "Dein Team verliert ☠️",
```

2020-11-05 17:32 UTC, mwkroening commented on locales/de.ts
> +  "black-reaction-4": "Oh nein, Sie haben auf einen Attentäter geklickt ☠️",
```suggestion
  "black-reaction-4": "Oh nein, du hast auf einen Attentäter geklickt ☠️",
```

2020-11-05 17:32 UTC, mwkroening commented on locales/de.ts
> +  "negative-reaction-1": "Hoppla!",
```suggestion
  "negative-reaction-1": "Ups!",
```

2020-11-05 17:32 UTC, mwkroening commented on locales/de.ts
> +  "negative-reaction-3": `Das andere Team dankt Ihnen.`,
```suggestion
  "negative-reaction-3": `Das andere Team dankt euch.`,
```

2020-11-05 17:32 UTC, mwkroening commented on locales/de.ts
> +  "negative-reaction-4": "Keine Sorge, Sie haben Ihr Bestes versucht 💛.",
```suggestion
  "negative-reaction-4": "Keine Sorge, Ihr haben euer Bestes gegeben. 💛",
```

2020-11-05 17:32 UTC, mwkroening commented on locales/de.ts
> +  "negative-reaction-5": "Keine Sorge, Sie haben Ihr Bestes gegeben. 🤦",
```suggestion
  "negative-reaction-5": "🤦",
```

2020-11-05 17:32 UTC, mwkroening commented on locales/de.ts
> +  "rules-classic-teams": `Die Spieler werden in zwei Mannschaften aufgeteilt: <1>rot</1> und <3>blau</3>. Ein Spieler jeder Mannschaft wird zum Spymaster der Mannschaft gewählt 🕵️ - die anderen sind
```suggestion
  "rules-classic-teams": `Die Spieler werden in zwei Teams aufgeteilt: <1>rot</1> und <3>blau</3>. Ein Spieler jedes Teams wird zu dessen Geheimdienstchef gewählt 🕵️ - alle anderen sind Ermittler.`,
```

2020-11-05 17:32 UTC, mwkroening commented on locales/de.ts
> +  "rules-classic-grid": `Fünfundzwanzig Wortkarten werden zufällig in einem Gitter ausgelegt. Eine Anzahl dieser Wörter repräsentieren <1>rot</1> Agenten, eine Anzahl repräsentiert <3>blau</3> Agente
```suggestion
  "rules-classic-grid": `25 zufällige Wortkarten werden in einem 5-mal-5-Raster ausgelegt. Ein Teil dieser Wörter steht für <1>rote</1> Agenten, ein anderer Teil für <3>blaue</3> Agenten, eines für einen <5>Attentäter</5>, und die anderen repräsentieren <7>unbeteiligte Zuschauer</span>. Die Geheimdienstchefs der Teams kennen die Farben der einzelnen Wörter und geben ihrem Team abwechselnd Hinweise, damit sie die Wörter ihrer Farbe erraten.`,
```

2020-11-05 17:32 UTC, mwkroening commented on locales/de.ts
> +  "rules-classic-hints": `Jeder Hinweis darf nur aus einem einzigen Wort und einer Anzahl von Karten bestehen, auf die er sich bezieht. Der Spielleiter gibt einen Hinweis, der sich auf möglichst viel
```suggestion
  "rules-classic-hints": `Jeder Hinweis darf nur aus einem einzigen Wort und einer Anzahl von Karten bestehen, auf die er sich bezieht. Der Geheimdienstchef gibt einen Hinweis, der sich auf möglichst viele der Wörter auf den Karten seiner eigenen Agenten bezieht, aber nicht auf andere - er könnte sein Team versehentlich dazu bringen, eine Karte zu wählen, die einen unbeteiligten Zuschauer, einen gegnerischen Agenten oder den Attentäter darstellt.`,
```

2020-11-05 17:32 UTC, mwkroening commented on locales/de.ts
> +  "rules-hint-restrictions": `Das Wort des Hinweises kann frei gewählt werden, solange es keines der Wörter auf den Codenameskarten ist (und nicht enthält), die zu diesem Zeitpunkt noch auftauchen. P
```suggestion
  "rules-hint-restrictions": `Das Hinweiswort kann frei gewählt werden, solange es keines der Wörter ist (und nicht enthält), die zu diesem Zeitpunkt noch offen sind. Phonetische Hinweise sind typischerweise verboten.`,
```

2020-11-05 17:32 UTC, mwkroening commented on locales/de.ts
> +  "rules-turns": `Die Karten werden aufgedeckt, wenn Vermutungen angestellt werden. Außendienstmitarbeiter müssen mindestens eine Vermutung pro Runde anstellen, wobei sie eine falsche Vermutung und d
```suggestion
  "rules-turns": `Die Karten werden aufgedeckt, wenn Rateversuche werden. Ermittler müssen mindestens einen Rateversuch pro Runde tätigen, wobei sie einen Fehlschlag riskieren. Sie können ihren Zug auch zu jedem späteren Zeitpunkt freiwillig beenden. Sie können bis zu der vom Geheimdienstchef angegebenen Zahl plus eins (ein Bonus, um ein zuvor angedeutetes Wort zu finden) raten.`,
```

2020-11-05 17:32 UTC, mwkroening commented on locales/de.ts
> +  "rules-classic-game-end": `Das Spiel endet, wenn alle Agenten einer Mannschaft identifiziert sind (🏅), oder wenn eine Mannschaft den <1>Assassinen</1> identifiziert hat (☠️).`,
```suggestion
  "rules-classic-game-end": `Das Spiel endet, wenn alle Agenten einer Mannschaft identifiziert sind (🏅), oder wenn eine Mannschaft den <1>Attentäter</1> identifiziert hat (☠️).`,
```

2020-11-05 17:32 UTC, mwkroening commented on locales/de.ts
> +  "rules-duet-objective": `Zwei Spieler arbeiten zusammen, um 15 Wörter auf der Tafel zu finden.`,
```suggestion
  "rules-duet-objective": `Zwei Spieler arbeiten zusammen, um 15 Wörter auf dem Raster zu finden.`,
```

2020-11-05 17:32 UTC, mwkroening commented on locales/de.ts
> +  "rules-duet-grid": `Fünfundzwanzig Wortkarten werden zufällig in einem Raster angeordnet. Eine Anzahl dieser Wörter steht für <1>grün</1> Agenten, eine Anzahl steht für <3>Meuchelmörder</3>, und di
```suggestion
  "rules-duet-grid": `25 zufällige Wortkarten werden in einem 5-mal-5-Raster ausgelegt. Ein Teil dieser Wörter steht für <1>grüne</1> Agenten, ein anderer für <3>Attentäter</3>, und die restlichen für <5>unschuldige Zuschauer</5>. Jeder Spieler kennt 9 <7>grüne</7> Wörter, von denen sich einige mit der anderen Seite überschneiden.`,
```

2020-11-05 17:32 UTC, mwkroening commented on locales/de.ts
> +  "rules-duet-hints": `Die Spieler geben abwechselnd Hinweise, damit der andere Spieler seine grüne Karte findet. Jeder Hinweis darf nur aus einem einzigen Wort und einer Anzahl von Karten bestehen,
```suggestion
  "rules-duet-hints": `Die Spieler geben abwechselnd Hinweise, damit der andere Spieler seine grüne Karte errät. Jeder Hinweis darf nur aus einem einzigen Wort und einer Anzahl von Karten bestehen, auf die er sich bezieht. Der Geheimdienstchef gibt einen Hinweis, der sich auf möglichst viele der Wörter auf den Karten seiner eigenen Agenten bezieht, aber nicht auf andere - sie könnten den anderen Spieler versehentlich dazu verleiten, eine Karte zu wählen, die einen unschuldigen Zuschauer oder einen Attentäter darstellt`,
```

2020-11-05 17:32 UTC, mwkroening commented on locales/de.ts
> +  "rules-duet-game-end": `Das Spiel endet, wenn alle 15 grünen Agenten identifiziert sind (🏅), oder wenn ein Spieler einen <1>Assassinen</1> identifiziert hat (☠️). Das Spiel ist zeitgesteuert, was b
```suggestion
  "rules-duet-game-end": `Das Spiel endet, wenn alle 15 grünen Agenten identifiziert sind (🏅), oder wenn ein Spieler einen <1>Assassinen</1> identifiziert hat (☠️). Das Spiel ist zeitbegrenzt. Beide Spieler haben insgesamt 9 Runden Zeit, um alle Wörter zu finden. Ein Klick auf einen <3>unschuldiger Zuschauer</Spanne> verbraucht einen zusätzlichen Zug.`,
```

2020-11-05 17:32 UTC, mwkroening commented on locales/de.ts
> +  "long-story-short": "Lange Geschichte-kurz",
```suggestion
  "long-story-short": "Langer Rede kurzer Sinn",
```

2020-11-05 17:32 UTC, mwkroening commented on locales/de.ts
> +  <p> Unser Analytik - Anbieter ist Google Analytics.< /p>
```suggestion
  <p> Unser Trackingtool ist Google Analytics.< /p>
```

2020-11-05 19:37 UTC, benjamintd reviewed
This is great, @mwkroening. Thanks so much.

2020-11-05 19:37 UTC, benjamintd commented on locales/de.ts
> +  "long-story-short": "Lange Geschichte-kurz",
this is lovely

2020-11-06 13:27 UTC, mwkroening requested changes
These are my final remarks.

Otherwise, it looks good to me. Thanks!

2020-11-06 13:27 UTC, mwkroening commented on locales/de.ts
> +  "page-title": "Codenames - Online spielen",
```suggestion
  "page-title": "Codenames online spielen",
```

2020-11-06 13:27 UTC, mwkroening commented on locales/de.ts
> +  "game-created": "Das Spiel wurde erstellt.",
```suggestion
  "game-created": "Spiel erstellt.",
```

2020-11-06 13:27 UTC, mwkroening commented on locales/de.ts
> +  "rules-turns": `Die Karten werden aufgedeckt, wenn Rateversuche werden. Ermittler müssen mindestens einen Rateversuch pro Runde tätigen, wobei sie einen Fehlschlag riskieren. Sie können ihren Zug a
```suggestion
  "rules-turns": `Die Karten werden aufgedeckt, wenn geraten wird. Ermittler müssen mindestens einen Rateversuch pro Runde tätigen, wobei sie einen Fehlschlag riskieren. Sie können ihren Zug auch zu jedem späteren Zeitpunkt freiwillig beenden. Sie können bis zu der vom Geheimdienstchef angegebenen Zahl plus eins (ein Bonus, um ein zuvor angedeutetes Wort zu finden) raten.`,
```

2020-11-06 13:27 UTC, mwkroening commented on locales/de.ts
> +  "rules-duet-game-end": `Das Spiel endet, wenn alle 15 grünen Agenten identifiziert sind (🏅), oder wenn ein Spieler einen <1>Assassinen</1> identifiziert hat (☠️). Das Spiel ist zeitbegrenzt. Beide
```suggestion
  "rules-duet-game-end": `Das Spiel endet, wenn alle 15 grünen Agenten identifiziert sind (🏅), oder wenn ein Spieler einen <1>Attentäter</1> identifiziert hat (☠️). Das Spiel ist zeitbegrenzt. Beide Spieler haben insgesamt 9 Runden Zeit, um alle Wörter zu finden. Ein Klick auf einen <3>unschuldiger Zuschauer</Spanne> verbraucht einen zusätzlichen Zug.`,
```

2020-11-06 16:34 UTC, benjamintd commented
Thank you @mwkroening. I could not have merged it without your help!

2020-11-06 16:34 UTC, merged